LOCAL_PROPERTIES = 'local.properties'
APP_PORT = 'port'
DB_HOST = "DB_HOST"
DB_PASSWORD = "DB_PASSWORD"
DB_USER = "DB_USER"
DB_NAME = "DB_NAME"
SECRET_KEY = "SECRET_KEY"
SQLALCHEMY_DATABASE_URI = "SQLALCHEMY_DATABASE_URI"


TABLE_EQUIPO = "equipo"
TABLE_JUGADOR = "jugador"
TABLE_JUGADOR_PERFIL = "jugador_perfil"
TABLE_PAIS = "pais"
TABLE_PERFIL = "perfil"
TABLE_PIE = "pie"
TABLE_POSICION = "posicion"
TABLE_SCOUT = "scout"
TABLE_SEGUIMIENTO = "seguimiento"
TABLE_SOMATOTIPO = "somatotipo"
TABLE_VALORACION = "valoracion"
TABLE_VISUALIZACION = "visualizacion"

URL_PARAM_ID = 'id'
URL_PARAM_ID_VALORACION = 'id_valoracion'
URL_PARAM_ID_JUGADOR = 'id_jugador'
URL_PARAM_DESCRIPCION = 'desc'
URL_PARAM_MIN = 'min'
URL_PARAM_NOMBRE = 'nombre'
URL_PARAM_ORDER_BY= 'order_by'

ACTIVE_YES ='Y'
ACTIVE_NO = 'N'
